name: build

on:
  push:
    branches:
      - master
      - 'renovate/**'

  pull_request:

env:
  DRY_RUN: ${{ github.ref != 'refs/heads/master' }}
  # https://github.com/chalk/supports-color/issues/106
  FORCE_COLOR: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flavor: [latest, 18.04, 20.04]

    env:
      FLAVOR: ${{ matrix.flavor }}
      FLAVOR_TAG: ${{ matrix.flavor }}

    steps:

      - uses: actions/checkout@v2

      - name: Docker registry login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Fix flavor
        run: |
          FLAVOR_TAG=${FLAVOR_TAG/18.04/bionic}
          FLAVOR_TAG=${FLAVOR_TAG/20.04/focal}
          echo "::set-env name=FLAVOR_TAG::${FLAVOR_TAG}"

      - name: Build and Publish
        uses: renovatebot/internal-tools@v0
        with:
          command: docker-builder
          build-args: FLAVOR
          major-minor: false
          prune: true
          tag-suffix: ${{ env.FLAVOR_TAG }}
          dry-run: ${{ env.DRY_RUN || env.FLAVOR != 'latest'}}
