name: build

on:
  push:
    branches:
      - master
      - 'renovate/**'

  pull_request:

env:
  LATEST_FLAVOR: 18.04
  # https://github.com/chalk/supports-color/issues/106
  FORCE_COLOR: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flavor: [18.04, 20.04]

    env:
      FLAVOR: ${{ matrix.flavor }}

    steps:

      - uses: actions/checkout@v2

      - name: Docker registry login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Publish
        uses: renovatebot/internal-tools@v0
        with:
          command: docker-builder
          build-args: FLAVOR
          major-minor: false
          prune: true
          tag-suffix: ${{ env.FLAVOR }}
          dry-run: ${{github.ref != 'refs/heads/master'}}

      - name: Build and Publish (no flavor)
        if: ${{ env.FLAVOR == env.LATEST_FLAVOR }}
        uses: renovatebot/internal-tools@v0
        with:
          command: docker-builder
          build-args: FLAVOR
          major-minor: false
          prune: true
          dry-run: ${{ env.DRY_RUN }}
